[package]
name = "ojo_diff"
description = "A small crate for computing diffs (part of the ojo project)"
version.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]

[dev-dependencies]
proptest = "0.8"
