[package]
name = "jp"
version = "0.1.0"
authors = ["Joe Neeman <joeneeman@gmail.com>"]

[dependencies]
    diff = { path = "../diff" }
    libjp = { path = "../libjp" }

[[bin]]
name = "new"
path = "src/new.rs"

[[bin]]
name = "show"
path = "src/show.rs"

