[package]
name = "jp"
version = "0.1.0"
authors = ["Joe Neeman <joeneeman@gmail.com>"]
edition = "2018"

[dependencies]
diff = { path = "../diff" }
libjp = { path = "../libjp" }
tempfile = "3"

[dependencies.clap]
version = "2"
features = ["yaml"]

