[package]
name = "multimap"
version = "0.1.0"
authors = ["Joe Neeman <joeneeman@gmail.com>"]
edition = "2018"

[dependencies]
    rpds = { git = "https://github.com/jneem/rpds", branch = "rbset", features = ["serde"]}
    serde = "1.0"
    serde_derive = "1.0"
