[package]
name = "jp_multimap"
version = "0.1.0"
authors = ["Joe Neeman <joeneeman@gmail.com>"]
edition = "2018"

[dependencies]
    serde = "1.0"
    serde_derive = "1.0"

[dev-dependencies]
    serde_yaml = "0.7"
