[package]
name = "quilt_multimap"
version = "0.1.1"
authors = ["Joe Neeman <joeneeman@gmail.com>"]
edition = "2018"
description = "A barebones multimap (part of the quilt project)"
repository = "https://github.com/jneem/quilt"
license = "MIT/Apache-2.0"

[dependencies]
    serde = "1.0"
    serde_derive = "1.0"

[dev-dependencies]
    serde_yaml = "0.7"
