[package]
name = "ojo"
version = "0.1.0"
authors = ["Joe Neeman <joeneeman@gmail.com>"]
edition = "2018"
description = "An experimental and educational version control system"
repository = "https://github.com/jneem/ojo"
license = "MIT/Apache-2.0"

[dependencies]
askama_escape = "0.1"
colored = "1.6"
failure = "0.1.3"
flexi_logger = "0.10"
libojo = { path = "../libojo", version = "0.1.0" }
log = "0.4"
ojo_diff = { path = "../diff", version = "0.1.0" }
ojo_graph = { path = "../graph", version = "0.1.0" }
termion = "1.5"

[dependencies.clap]
version = "2"
features = ["yaml"]
